name: NuGet Release Workflow

on:
  release:
    types: [published]

jobs:
  make-upm-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install .NET
        if: steps.semantic.outputs.new_release_published == 'true'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            5.x
            6.x
            7.x
            8.x

      - name: Add NuGet Source
        run: dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

      - name: Pack NuGet Package
        run: dotnet pack -c Release -p:VERSION=${{ steps.semantic.outputs.new_release_version }} -o output

      - name: Publish to GitHub packages
        run: dotnet nuget push output/*.nupkg --skip-duplicate --api-key ${{ secrets.GITHUB_TOKEN }} --source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json

      - name: Publish to NuGet
        run: dotnet nuget push output/*.nupkg --skip-duplicate --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json