name: Sync Unity Project
on:
  workflow_call:
    secrets:
      unity_license:
        required: true
      access_token:
        required: true
    inputs:
      cache_key:
        type: string
        required: true

jobs:
  sync:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2021.3.0f1-base-3.0.0
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache library
        uses: actions/cache@v3.0.11
        with:
          path: ./Unity/Library
          key: ${{ inputs.cache_key }}

      - name: Install rsync
        run: |
          apt-get update -y
          apt-get install rsync -y

      - name: Remove old files
        run: |
          find ./Unity/Packages/se.hertzole.array-pool-scope/Runtime -name \*.cs -type f -delete
          find ./Unity/Packages/se.hertzole.array-pool-scope/Tests/Runtime -name \*.cs -type f -delete

      - name: Copy files
        run: |
          chmod +x ./ci/move_to_unity.sh
          ./ci/move_to_unity.sh

      - name: Activate Unity
        continue-on-error: true
        env:
          UNITY_LICENSE: ${{ secrets.unity_license }}
        run: |
          echo "$UNITY_LICENSE" | tr -d '\r' > License.ulf
          unity-editor -nographics -logFile /dev/stdout -manualLicenseFile License.ulf -quit

      - run: cat Unity/Packages/se.hertzole.array-pool-scope/Tests/Runtime/Hertzole.ArrayPoolScope.Tests.asmdef

      - name: Import project
        run: unity-editor -nographics -logFile /dev/stdout -projectPath ./Unity/ -quit

      - name: Remove empty directories
        run: |
          chmod +x ./ci/remove_empty_folders.sh
          ./ci/remove_empty_folders.sh ./Unity/Packages/se.hertzole.array-pool-scope/

      - name: Upload package artifacts
        uses: actions/upload-artifact@v4.3.1
        with:
          name: unity-package-folder
          path: ./Unity/Packages/se.hertzole.array-pool-scope/

      - name: Commit
        # I can't for the life of me get a conditional to work here. So if it fails, ignore it. ¯\_(ツ)_/¯
        continue-on-error: true
        run: |
          git config --global --add safe.directory /__w/array-pool-scope/array-pool-scope
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git add ./Unity/
          git commit -am "chore: synced unity from '${{ github.event.head_commit.message }}'"
          git push -f -u origin ${{ github.ref }}
