name: Release Workflow

on:
  release:
    types: [published]

jobs:
  make-upm-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create UPM package
        run: |
          git branch -d upm &> /dev/null || echo upm branch not found
          git subtree split -P "$PKG_ROOT" -b upm
          if [[ -d "Assets/Samples" ]]; then
            mv "Assets/Samples" /tmp/example
          fi
          if [[ -f "CHANGELOG.md" ]]; then
            mv CHANGELOG.md /tmp/CHANGELOG.md
          fi
          if [[ -f "LICENSE" ]]; then
            mv LICENSE /tmp/LICENSE
          fi
          if [[ -f "README.md" ]]; then
            mv README.md /tmp/README.md
          fi
          git checkout upm
          if [[ -f "/tmp/README.md" ]]; then
            mv /tmp/README.md README.md
            git add README.md
          fi
          if [[ -d "/tmp/example" ]]; then
            mkdir "Samples~"
            mv /tmp/example/* "Samples~/"
            git add "Samples~"
          fi
          if [[ -f "/tmp/CHANGELOG.md" ]]; then
            mv /tmp/CHANGELOG.md CHANGELOG.md
            git add CHANGELOG.md
          fi
          if [[ -f "/tmp/LICENSE" ]]; then
            mv /tmp/LICENSE LICENSE
            git add LICENSE
          fi
          if [[ -d "Tests" ]]; then
            rm -rf Tests
            rm -f Tests.meta
          fi
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git commit -am "chore: create upm package"
          git push -f -u origin upm
        env:
          PKG_ROOT: "Unity/Packages/se.hertzole.array-pool-scope"
        shell: bash